---
- name: Converge
  hosts: all
  vars:
    zabbix_agent_version: 3.0
    zabbix_agent_debuglevel: 4
    zabbix_agent_hostname: "{{ inventory_hostname }}"
    zabbix_agent_server: 192.168.0.10
    zabbix_agent_startagents: 5
    zabbix_agent_hostmetadataitem: system.uname
    zabbix_agent_timeout: 20
    zabbix_agent_include:
      - /usr/local/etc/*.conf
      - /usr/local/lib/*.conf
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
